# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: xenial
repos:
  CRAN: https://cloud.r-project.org
  PIK:  https://rse.pik-potsdam.de/r/packages/
cache: packages
latex: false
pandoc: false
r_packages:
  - gms
install:
  - Rscript -e "if(!requireNamespace('gms')) install.packages('gms')"
script:
  - Rscript -e "null <- gms::codeCheck(strict=TRUE)"
